-- P2DBOWN.T_ORDER definition

CREATE TABLE "P2DBOWN"."T_ORDER" 
   (	"T_ORDER_UID" NUMBER(10,0) DEFAULT "P2DBOWN"."T_ORDER_UID_SEQ".NEXTVAL NOT NULL ENABLE, 
	"ORDER_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"BR_NO" NUMBER(2,0) NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(100), 
	"RELEASED_DATE" TIMESTAMP (6), 
	"JOB_CODE" VARCHAR2(50), 
	"CLASS_CODE" VARCHAR2(50), 
	"PLN_START_DATE" TIMESTAMP (6), 
	"PLN_COMPLETE_DATE" TIMESTAMP (6), 
	"CLOSED_DATE" TIMESTAMP (6), 
	"STARTED_DTIME" TIMESTAMP (6), 
	"COMPLETED_DTIME" TIMESTAMP (6), 
	"QTY" NUMBER(10,0), 
	"COMPLETED_QTY" NUMBER(10,0), 
	"DISPOSED_QTY" NUMBER(10,0), 
	"DEFECTIVE_QTY" NUMBER(10,0), 
	"DESTRUCTIVE_INSP_QTY" NUMBER(10,0), 
	"OVER_CMPLT_LIMIT" NUMBER(10,0), 
	"REQ_OUTPUT_TYPE" VARCHAR2(50), 
	"PICK_REL_FLAG" CHAR(1), 
	"MNFG_ORDER_FLAG" CHAR(1), 
	"PLANNER_CODE" VARCHAR2(50), 
	"GROUP_ID" VARCHAR2(50), 
	"PLANNER_GROUP_CODE" VARCHAR2(50), 
	"CMM_RT_ITEM_CODE" VARCHAR2(50), 
	"STATUS_CODE" VARCHAR2(50), 
	"KANBAN_ID" VARCHAR2(50), 
	"PRODUCT_CYCLE" VARCHAR2(50), 
	"CARD_STATUS_CODE" VARCHAR2(50), 
	"SPLY_STATUS_CODE" VARCHAR2(50), 
	"ONEWAY_KB_OUT_FLAG" CHAR(1), 
	"STOCK_ID" VARCHAR2(50), 
	"STOCK_NAME" VARCHAR2(100), 
	"STOCK_SNAME" VARCHAR2(50), 
	"PARTY_ID" VARCHAR2(50), 
	"PARTY_KEY_ID" VARCHAR2(50), 
	"PARTY_KEY_CONT_ID" VARCHAR2(50), 
	"PARTY_ORGN_NAME" VARCHAR2(100), 
	"PARTY_DEPT_CODE" VARCHAR2(50), 
	"PARENT_ORGN_NAME" VARCHAR2(100), 
	"ITEM_ID" VARCHAR2(255 CHAR), 
	"ITEM_APP_OBJKEY_ID" VARCHAR2(50), 
	"ITEM_NAME" VARCHAR2(100), 
	"UNIT_MEASURE_CODE" VARCHAR2(10), 
	"STORAGE_ID" VARCHAR2(50), 
	"MODEL" VARCHAR2(100), 
	"SPECIFICATION" VARCHAR2(100), 
	"DETAIL" VARCHAR2(100), 
	"LOT_CTRL_CODE" VARCHAR2(50), 
	"PICK_CONTACT" VARCHAR2(50), 
	"BACK_NO" VARCHAR2(50), 
	"REV_SYM" VARCHAR2(10), 
	"LOT_NO_CODE" VARCHAR2(50), 
	"ITEM_CAT_ID" VARCHAR2(50), 
	"ITEM_CAT_NAME" VARCHAR2(100), 
	"STAT_ITEM_CAT_CODE" VARCHAR2(50), 
	"STAT_FAMILY" VARCHAR2(50), 
	"STAT_FAMILY_DETAIL" VARCHAR2(100), 
	"MM_CAT_CODE" VARCHAR2(50), 
	"MM_TYPE_FAMILY" VARCHAR2(50), 
	"WIP_CAT_CODE" VARCHAR2(50), 
	"WIP_MASS_CAT_CODE" VARCHAR2(50), 
	"SELF_OPE_NAME" VARCHAR2(100), 
	"FINISH" VARCHAR2(50), 
	"MATERIAL" VARCHAR2(50), 
	"MFGST_ID" VARCHAR2(50), 
	"CO_SLIP_NO" VARCHAR2(50), 
	"ISSUED_FLAG" CHAR(1), 
	"ROHS_FLAG" CHAR(1), 
	"COS_EFFECT_FLAG" CHAR(1), 
	"COSNO_COUNT" NUMBER(10,0), 
	"TRACE_IF_FLAG" CHAR(1), 
	"PROCESS_MNG_FLAG" CHAR(1), 
	"NOTES1" VARCHAR2(100), 
	"NOTES2" VARCHAR2(100), 
	"STATUS" VARCHAR2(50), 
	"BOUND_FLAG" CHAR(1), 
	"ORDER_NAME" VARCHAR2(100), 
	"CREATED_BY" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(10), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	 CONSTRAINT "PK_T_ORDER" PRIMARY KEY ("T_ORDER_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "P2DBOWN"."T_ORDER_BI_TRG" 
BEFORE INSERT ON "P2DBOWN"."T_ORDER"
FOR EACH ROW
BEGIN
  IF :NEW."T_ORDER_UID" IS NULL THEN
    SELECT "P2DBOWN"."T_ORDER_UID_SEQ".NEXTVAL INTO :NEW."T_ORDER_UID" FROM DUAL;
  END IF;
END;
/
ALTER TRIGGER "P2DBOWN"."T_ORDER_BI_TRG" ENABLE;

CREATE UNIQUE INDEX "P2DBOWN"."PK_T_ORDER" ON "P2DBOWN"."T_ORDER" ("T_ORDER_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;