-- P2DBOWN.T_PROCESS definition

CREATE TABLE "P2DBOWN"."T_PROCESS" 
   (	"T_PROCESS_UID" NUMBER(20,0) NOT NULL ENABLE, 
	"T_ORDER_UID" NUMBER(20,0) NOT NULL ENABLE, 
	"ORDER_NO" VARCHAR2(10) NOT NULL ENABLE, 
	"BR_NO" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"MF_ORD_NO" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(240), 
	"MF_SEQ_NO" NUMBER, 
	"DESCRIPTION" VARCHAR2(240), 
	"FUT_START_DATE" DATE, 
	"FUT_START_TIME" DATE, 
	"FUT_COMPLETE_DATE" DATE, 
	"LAST_MOVED_DATE" DATE, 
	"OPERATION_CODE" VARCHAR2(4), 
	"DEPT_CODE" VARCHAR2(10), 
	"DEPT_NAME" VARCHAR2(240), 
	"ONHAND_QTY" NUMBER, 
	"RUNNING_VAL_DATE" DATE, 
	"PLN_START_DATE" DATE NOT NULL ENABLE, 
	"PLN_COMPLETE_DATE" DATE NOT NULL ENABLE, 
	"LINE_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CYCLE_NUM" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE, 
	"SMT_SIDE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"SCH_INJECT_QTY" NUMBER NOT NULL ENABLE, 
	"SCH_START_DTIME" DATE, 
	"SCH_COMPLETE_DTIME" DATE, 
	"READY_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"INJECTED_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DEFECTIVE_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DISPOSED_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"COMPLETED_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DESTRUCTIVE_INSP_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PREPARED_DTIME" DATE, 
	"STARTED_DTIME" DATE, 
	"COMPLETED_DTIME" DATE, 
	"LINEOUT_QTY" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CR_STAFF" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"CR_PRP_TIME" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"CR_MFG_TIME" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"APPL_MH" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"AC_STAFF" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PDCT_TIME" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"MULTI_DV_FLAG" CHAR(1) DEFAULT '0' NOT NULL ENABLE, 
	"PROCESS_MNG_FLAG" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE, 
	"NOTES" VARCHAR2(150), 
	"PRP_STATUS" CHAR(1) NOT NULL ENABLE, 
	"LOT_TRACE_CHECK_TYPE" CHAR(1) DEFAULT '0' NOT NULL ENABLE, 
	"STATUS" CHAR(1) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(10), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "P2DBOWN"."TRG_T_PROCESS" 
BEFORE INSERT ON P2DBOWN.T_PROCESS
FOR EACH ROW
DECLARE
BEGIN
	IF :NEW.T_PROCESS_UID IS NULL THEN
		SELECT SEQ_T_PROCESS_1.NEXTVAL
		INTO :NEW.T_PROCESS_UID
		FROM DUAL;
	END IF;
END;
/
ALTER TRIGGER "P2DBOWN"."TRG_T_PROCESS" ENABLE;

COMMENT ON COLUMN P2DBOWN.T_PROCESS.T_PROCESS_UID IS '進捗情報UID';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.T_ORDER_UID IS 'オーダ情報UID';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.ORDER_NO IS 'オーダNO';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.BR_NO IS '枝番';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.MF_ORD_NO IS '工程順序NO';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.ORDER_ID IS '製造オーダ番号';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.MF_SEQ_NO IS '工程連番';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.DESCRIPTION IS '摘要';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.FUT_START_DATE IS '第一単位開始日';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.FUT_START_TIME IS '第一単位開始時間';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.FUT_COMPLETE_DATE IS '第一単位完了日';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.LAST_MOVED_DATE IS '前回移動日付';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.OPERATION_CODE IS '標準工程';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.DEPT_CODE IS '部門コード';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.DEPT_NAME IS '部門名称';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.ONHAND_QTY IS '手持在庫数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.RUNNING_VAL_DATE IS '仕掛評価日';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.PLN_START_DATE IS '着手日';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.PLN_COMPLETE_DATE IS '完了日';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.LINE_ID IS 'ラインID';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.CYCLE_NUM IS 'サイクル番号';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.SMT_SIDE IS '実装面';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.SCH_INJECT_QTY IS '投入予定数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.SCH_START_DTIME IS '着手予定日時';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.SCH_COMPLETE_DTIME IS '完了予定日時';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.READY_QTY IS '投入待ち数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.INJECTED_QTY IS '投入済み数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.DEFECTIVE_QTY IS '不良数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.DISPOSED_QTY IS '廃棄済み数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.COMPLETED_QTY IS '完了済み数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.DESTRUCTIVE_INSP_QTY IS '破壊検査数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.PREPARED_DTIME IS '内段取着手日時';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.STARTED_DTIME IS '実績着手日時';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.COMPLETED_DTIME IS '実績完了日時';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.LINEOUT_QTY IS 'ラインアウト数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.CR_STAFF IS '基準人員';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.CR_PRP_TIME IS '基準内段取時間';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.CR_MFG_TIME IS '基準製造時間';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.APPL_MH IS '適用工数';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.AC_STAFF IS '実際人員';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.PDCT_TIME IS '生産時間';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.MULTI_DV_FLAG IS '分納フラグ';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.PROCESS_MNG_FLAG IS '進捗管理対象フラグ';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.NOTES IS 'コメント';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.PRP_STATUS IS '外段取状態';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.LOT_TRACE_CHECK_TYPE IS 'ロットトレースチェックタイプ';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.STATUS IS '状態';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.CREATED_BY IS '作成者ID';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.CREATE_TIMESTAMP IS '作成日時';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.UPDATED_BY IS '更新者ID';
COMMENT ON COLUMN P2DBOWN.T_PROCESS.UPDATE_TIMESTAMP IS '更新日時';