-- P2DBOWN.T_SMT_NG definition

CREATE TABLE "P2DBOWN"."T_SMT_NG" 
   (	"T_SMT_NG_UID" NUMBER NOT NULL ENABLE, 
	"LINE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"ORDER_NO" VARCHAR2(10) NOT NULL ENABLE, 
	"BR_NO" NUMBER(2,0) NOT NULL ENABLE, 
	"MOUNTER_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"SMT_SIDE" VARCHAR2(2) NOT NULL ENABLE, 
	"PART_ID" VARCHAR2(10), 
	"SMT_PROCESS" VARCHAR2(40) NOT NULL ENABLE, 
	"SMT_CONTENT" VARCHAR2(200) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	 CONSTRAINT "PK_T_SMT_NG" PRIMARY KEY ("T_SMT_NG_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 48234496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 463470592 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "P2DBOWN"."TRG_T_SMT_NG" 
BEFORE INSERT ON T_SMT_NG
FOR EACH ROW
DECLARE
BEGIN
	IF :NEW.T_SMT_NG_UID IS NULL THEN
		SELECT SEQ_T_SMT_NG_1.NEXTVAL
		INTO :NEW.T_SMT_NG_UID
		FROM DUAL;
	END IF;
END;

/
ALTER TRIGGER "P2DBOWN"."TRG_T_SMT_NG" ENABLE;

CREATE UNIQUE INDEX "P2DBOWN"."PK_T_SMT_NG" ON "P2DBOWN"."T_SMT_NG" ("T_SMT_NG_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 48234496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;