-- P2DBOWN.T_SMT_PROCESS definition

CREATE TABLE "P2DBOWN"."T_SMT_PROCESS" 
   (	"T_SMT_PROCESS_UID" NUMBER NOT NULL ENABLE, 
	"ORDER_NO" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"BR_NO" NUMBER NOT NULL ENABLE, 
	"MOUNTER_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"SMT_SIDE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"WORKER_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"SMT_PROCESS" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	 CONSTRAINT "PK_T_SMT_PROCESS" PRIMARY KEY ("T_SMT_PROCESS_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 44040192 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 240123904 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "P2DBOWN"."TRG_T_SMT_PROCESS" 
BEFORE INSERT ON T_SMT_PROCESS
FOR EACH ROW
DECLARE
BEGIN
	IF :NEW.T_SMT_PROCESS_UID IS NULL THEN
		SELECT SEQ_T_SMT_PROCESS_1.NEXTVAL
		INTO :NEW.T_SMT_PROCESS_UID
		FROM DUAL;
	END IF;
END;

/
ALTER TRIGGER "P2DBOWN"."TRG_T_SMT_PROCESS" ENABLE;

CREATE UNIQUE INDEX "P2DBOWN"."PK_T_SMT_PROCESS" ON "P2DBOWN"."T_SMT_PROCESS" ("T_SMT_PROCESS_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 44040192 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;