-- P2DBOWN.T_SMT_ROLL definition

CREATE TABLE "P2DBOWN"."T_SMT_ROLL" 
   (	"T_SMT_ROLL_UID" NUMBER NOT NULL ENABLE, 
	"ORDER_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"BR_NO" NUMBER(2,0) NOT NULL ENABLE, 
	"MOUNTER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SMT_SIDE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PART_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LOT_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ORD_NO" NUMBER, 
	"ROLL_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SMT_PROCESS" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"WORKER_ID" VARCHAR2(255 CHAR), 
	 CONSTRAINT "PK_T_SMT_ROLL" PRIMARY KEY ("T_SMT_ROLL_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 192937984 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2013265920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "P2DBOWN"."TRG_T_SMT_ROLL" 
BEFORE INSERT ON T_SMT_ROLL
FOR EACH ROW
DECLARE
BEGIN
	IF :NEW.T_SMT_ROLL_UID IS NULL THEN
		SELECT SEQ_T_SMT_ROLL_1.NEXTVAL
		INTO :NEW.T_SMT_ROLL_UID
		FROM DUAL;
	END IF;
END;

/
ALTER TRIGGER "P2DBOWN"."TRG_T_SMT_ROLL" ENABLE;

CREATE UNIQUE INDEX "P2DBOWN"."PK_T_SMT_ROLL" ON "P2DBOWN"."T_SMT_ROLL" ("T_SMT_ROLL_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 192937984 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;