CREATE TABLE "P2DBOWN"."TM_MOUNTER" 
   (	"MOUNTER_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"MOUNTER_NAME" VARCHAR2(60), 
	"MOUNTER_TYPE" VARCHAR2(8) NOT NULL ENABLE, 
	"OLD_ROLL_OFFSET" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"LINE_ID" VARCHAR2(10), 
	"MOUNTER_SEQ" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"ACTIVE_FLAG" CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(10), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	 CONSTRAINT "PK_TM_MOUNTER" PRIMARY KEY ("MOUNTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "P2DBOWN"."PK_TM_MOUNTER" ON "P2DBOWN"."TM_MOUNTER" ("MOUNTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "P2DBOWN"."IDX_TM_MOUNTER_1" ON "P2DBOWN"."TM_MOUNTER" ("LINE_ID", "MOUNTER_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;