-- P2DBOWN.TM_MOUNTER_TYPE definition

CREATE TABLE "P2DBOWN"."TM_MOUNTER_TYPE" 
   (	"MOUNTER_TYPE" VARCHAR2(8) NOT NULL ENABLE, 
	"MOUNTER_TYPE_NAME" VARCHAR2(60), 
	"MAX_ROLL_NUM" NUMBER(3,0) NOT NULL ENABLE, 
	"LOT_TRACE_IF_FLAG" CHAR(1) DEFAULT '0' NOT NULL ENABLE, 
	"ACTIVE_FLAG" CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(10), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	 CONSTRAINT "PK_TM_MOUNTER_TYPE" PRIMARY KEY ("MOUNTER_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "P2DBOWN"."PK_TM_MOUNTER_TYPE" ON "P2DBOWN"."TM_MOUNTER_TYPE" ("MOUNTER_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;