-- P2DBOWN.TM_ROLL_MNG definition

CREATE TABLE "P2DBOWN"."TM_ROLL_MNG" 
   (	"PCB_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SMT_SIDE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MOUNTER_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PRODUCT_ATTRIB" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ROLL_MNG_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"REMARK1" VARCHAR2(255 CHAR), 
	"REMARK2" VARCHAR2(255 CHAR), 
	"REMARK3" VARCHAR2(255 CHAR), 
	"ACTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	 CONSTRAINT "PK_TM_ROLL_MNG" PRIMARY KEY ("PCB_ID", "SMT_SIDE", "MOUNTER_TYPE", "PRODUCT_ATTRIB", "ACTIVE_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "P2DBOWN"."PK_TM_ROLL_MNG" ON "P2DBOWN"."TM_ROLL_MNG" ("PCB_ID", "SMT_SIDE", "MOUNTER_TYPE", "PRODUCT_ATTRIB", "ACTIVE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;