CREATE TABLE "P2DBOWN"."TM_ROLL" 
   (	"ROLL_MNG_NO" VARCHAR2(32) NOT NULL ENABLE, 
	"STATION_NO" NUMBER(2,0) NOT NULL ENABLE, 
	"ROLL_NO" NUMBER(4,0) NOT NULL ENABLE, 
	"PART_ID" VARCHAR2(40) NOT NULL ENABLE, 
	"QTY" NUMBER NOT NULL ENABLE, 
	"FIXED_FLAG" CHAR(1) NOT NULL ENABLE, 
	"ACTIVE_FLAG" CHAR(1) NOT NULL ENABLE, 
	"LOCATION_COMMENT" VARCHAR2(2000), 
	"CREATED_BY" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(10), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 186646528 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;