ALTER TABLE P2DBOWN.TM_STORAGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE P2DBOWN.TM_STORAGE CASCADE CONSTRAINTS;

CREATE TABLE P2DBOWN.TM_STORAGE
(
  STOCK_ID          VARCHAR2(10 BYTE)           NOT NULL,
  ITEM_ID           VARCHAR2(40 BYTE)           NOT NULL,
  STORAGE_ID        VARCHAR2(150 BYTE),
  ALTO_METHOD       CHAR(1 BYTE),
  SORT_BY           NUMBER(6),
  ACTIVE_DATE       DATE                        DEFAULT TRUNC(SYSDATE)        NOT NULL,
  EXPIRE_DATE       DATE,
  CREATED_BY        VARCHAR2(10 BYTE)           NOT NULL,
  CREATE_TIMESTAMP  TIMESTAMP(6)                DEFAULT SYSTIMESTAMP          NOT NULL,
  UPDATED_BY        VARCHAR2(10 BYTE),
  UPDATE_TIMESTAMP  TIMESTAMP(6)
)
TABLESPACE P2DBTBL
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.STOCK_ID IS '保管場所ID';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.ITEM_ID IS '品番';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.STORAGE_ID IS '棚番';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.ALTO_METHOD IS '配当方法';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.SORT_BY IS 'ソート順';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.ACTIVE_DATE IS '有効開始日';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.EXPIRE_DATE IS '失効日';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.CREATED_BY IS '作成者ID';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.CREATE_TIMESTAMP IS '作成日時';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.UPDATED_BY IS '更新者ID';

COMMENT ON COLUMN P2DBOWN.TM_STORAGE.UPDATE_TIMESTAMP IS '更新日時';



CREATE UNIQUE INDEX P2DBOWN.PK_TM_STORAGE ON P2DBOWN.TM_STORAGE
(STOCK_ID, ITEM_ID, ACTIVE_DATE)
LOGGING
TABLESPACE P2DBIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE SYNONYM MESIFOWN.P2_TM_STORAGE FOR P2DBOWN.TM_STORAGE;


CREATE OR REPLACE SYNONYM P2DBOPE.TM_STORAGE FOR P2DBOWN.TM_STORAGE;


CREATE OR REPLACE SYNONYM P2DBOWN.OLD_TM_STORAGE FOR MESUSER.TM_STORAGE;


CREATE OR REPLACE SYNONYM P2DBOWN.P2_TM_STORAGE FOR P2DBOWN.TM_STORAGE;


ALTER TABLE P2DBOWN.TM_STORAGE ADD (
  CONSTRAINT PK_TM_STORAGE
  PRIMARY KEY
  (STOCK_ID, ITEM_ID, ACTIVE_DATE)
  USING INDEX P2DBOWN.PK_TM_STORAGE
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON P2DBOWN.TM_STORAGE TO MESIFOWN;

GRANT SELECT ON P2DBOWN.TM_STORAGE TO P2DBOPE;

GRANT DELETE, INSERT, SELECT, UPDATE ON P2DBOWN.TM_STORAGE TO P2DBTRN;