CREATE TABLE "P2DBOWN"."TM_WORKER" 
   (	"WORKER_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"WORKER_NAME" VARCHAR2(60), 
	"WORKER_GRP_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"WORKER_TYPE" VARCHAR2(8), 
	"IC_ID" VARCHAR2(20), 
	"ACTIVE_FLAG" CHAR(1) DEFAULT '0' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(10) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TM_WORKER" PRIMARY KEY ("WORKER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE "P2DBOWN"."TM_WORKER" IS '工作人员信息表';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."WORKER_ID" IS '工作人员ID';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."WORKER_NAME" IS '工作人员姓名';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."WORKER_GRP_ID" IS '工作组ID';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."WORKER_TYPE" IS '工作人员类型';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."IC_ID" IS '身份证号';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."ACTIVE_FLAG" IS '激活标志（0-未激活，1-激活）';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."CREATED_BY" IS '创建人';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."CREATE_TIMESTAMP" IS '创建时间';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."UPDATED_BY" IS '更新人';
COMMENT ON COLUMN "P2DBOWN"."TM_WORKER"."UPDATE_TIMESTAMP" IS '更新时间';

CREATE UNIQUE INDEX "P2DBOWN"."PK_TM_WORKER" ON "P2DBOWN"."TM_WORKER" ("WORKER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;