ALTER TABLE MESIFOWN.TO_PICKING_SMT
 DROP PRIMARY KEY CASCADE;

DROP TABLE MESIFOWN.TO_PICKING_SMT CASCADE CONSTRAINTS;

CREATE TABLE MESIFOWN.TO_PICKING_SMT
(
  SEQ_NO            NUMBER                      DEFAULT 0                     NOT NULL,
  ORDER_NO          VARCHAR2(10 BYTE)           NOT NULL,
  BR_NO             NUMBER(2)                   NOT NULL,
  ITEM_ID           VARCHAR2(40 BYTE)           NOT NULL,
  ITEM_NAME         VARCHAR2(240 BYTE),
  GROUP_ID          VARCHAR2(40 BYTE),
  GROUP_NAME        VARCHAR2(240 BYTE),
  PART_ID           VARCHAR2(40 BYTE)           NOT NULL,
  PART_NAME         VARCHAR2(240 BYTE),
  STOCK_ID          VARCHAR2(10 BYTE)           NOT NULL,
  STORAGE_ID        VARCHAR2(150 BYTE)          NOT NULL,
  ITEM_QTY          NUMBER                      NOT NULL,
  PART_QTY          NUMBER                      NOT NULL,
  SMT_SIDE          CHAR(1 BYTE)                NOT NULL,
  LINE_ID           VARCHAR2(10 BYTE)           NOT NULL,
  LINE_NAME         VARCHAR2(240 BYTE),
  MOUNTER_TYPE      VARCHAR2(8 BYTE)            NOT NULL,
  MOUNTER_ID        VARCHAR2(10 BYTE)           NOT NULL,
  PROCESSFLAG       CHAR(1 BYTE)                DEFAULT 0                     NOT NULL,
  CLOSEDFLAG        CHAR(1 BYTE)                DEFAULT 0                     NOT NULL,
  EQUIPMENT_NO      VARCHAR2(10 BYTE)           NOT NULL,
  MOUNTER_COUNT     NUMBER                      NOT NULL,
  CREATED_BY        VARCHAR2(10 BYTE)           NOT NULL,
  CREATE_TIMESTAMP  TIMESTAMP(6)                NOT NULL,
  UPDATED_BY        VARCHAR2(10 BYTE),
  UPDATE_TIMESTAMP  TIMESTAMP(6)
)
TABLESPACE MESIFTBL
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MESIFOWN.PK_TO_PICKING_SMT ON MESIFOWN.TO_PICKING_SMT
(SEQ_NO)
LOGGING
TABLESPACE MESIFTBL
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MESIFOWN.TO_PICKING_SMT_INDEX1 ON MESIFOWN.TO_PICKING_SMT
("ORDER_NO" DESC, BR_NO)
LOGGING
TABLESPACE MESIFTBL
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER MESIFOWN."TRG_TO_PICKING_SMT" 
BEFORE INSERT ON MESIFOWN.TO_PICKING_SMT
FOR EACH ROW
DECLARE
BEGIN
	IF :NEW.SEQ_NO =0 THEN
		SELECT SEQ_TO_PICKING_SMT_1.NEXTVAL
		INTO :NEW.SEQ_NO
		FROM DUAL;
	END IF;
END;
/


CREATE OR REPLACE SYNONYM P2DBOWN.TO_PICKING_SMT FOR MESIFOWN.TO_PICKING_SMT;


ALTER TABLE MESIFOWN.TO_PICKING_SMT ADD (
  CONSTRAINT PK_TO_PICKING_SMT
  PRIMARY KEY
  (SEQ_NO)
  USING INDEX MESIFOWN.PK_TO_PICKING_SMT
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON MESIFOWN.TO_PICKING_SMT TO P2DBOWN;